### ISSUE TITLE
OpenType shaping not working

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Varta#2]
XP: 

![836wnpd - imgur](https://cloud.githubusercontent.com/assets/261579/7615497/4eaaea66-f99e-11e4-87ae-1172a329970e.png)

**Comment by behdad** [comment]
XP doesn't support 'dev2', etc.  I think this should be a wontfix.

**Comment by davelab6** [comment]
Is on Mac too

**Comment by davelab6** [comment]
When I use Safari Version 7.1.6 on Mac OS X 10.9 to review http://www.impallari.com/testing/index-devanagari.php#sample_one (you need to click the 'Sample 1' tab link near the top right) then the shaping isn't working :(
